import typer
import runpy
import json
import sys
import time
import os
import contextlib
from reqhound.main import Tracker, parse_requirements, get_explicit_imports

app = typer.Typer()

@app.command()
def run(script: str):
    tracker = Tracker()
    sys.meta_path.insert(0, tracker)

    to_delete = [
        k for k in sys.modules
        if k.split(".")[0] not in sys.stdlib_module_names
        and not k.split(".")[0].startswith("_")
    ]
    for k in to_delete:
        del sys.modules[k]

    with typer.progressbar(length=100, label="  scanning") as progress:
        with open(os.devnull, "w") as devnull:
            with contextlib.redirect_stdout(devnull), contextlib.redirect_stderr(devnull):
                try:
                    runpy.run_path(script)
                except Exception:
                    pass
        progress.update(100)

    explicit = get_explicit_imports(script)
    filtered = tracker.seen & explicit

    with open(".reqtrace.json", "w") as f:
        json.dump(sorted(filtered), f, indent=2)

    typer.secho(f"\ntracked {len(filtered)} packages → .reqtrace.json\n", fg=typer.colors.GREEN)

@app.command()
def export():
    """Write a clean requirements.txt from tracked imports."""
    with open(".reqtrace.json") as f:
        tracked = json.load(f)

    if not tracked:
        typer.secho("  no tracked imports. run `reqtrace run` first.", fg=typer.colors.RED)
        raise typer.Exit()

    with typer.progressbar(tracked, label="  writing ") as progress:
        lines = []
        for package in progress:
            lines.append(package)
            time.sleep(0.05)  
    with open("requirements.txt", "w") as f:
        f.write(f"# generated by reqtrace: github.com/itsf4lcon\n\n")
        for package in sorted(lines):
            f.write(package + "\n")

    os.remove(".reqtrace.json")        

    typer.secho(f"\nwritten {len(lines)} packages to requirements.txt\n", fg=typer.colors.GREEN)

@app.command()
def check():

    with open(".reqtrace.json") as f:
        tracked = set(json.load(f))
    required = parse_requirements()

    missing = tracked - required
    unused  = required - tracked
    present = tracked & required

    typer.echo("\n── reqtrace results ──────────────────")
    for p in sorted(present):
        typer.secho(f"{p}", fg=typer.colors.GREEN)
    for p in sorted(missing):
        typer.secho(f"{p}  ← missing from requirements.txt", fg=typer.colors.YELLOW)
    for p in sorted(unused):
        typer.secho(f"{p}  ← in requirements.txt but never imported", fg=typer.colors.RED)
    typer.echo("──────────────────────────────────────")
    typer.echo(f"  {len(present)} present  {len(missing)} missing  {len(unused)} unused\n")

if __name__ == "__main__":
    app()
